# 利用requests套件擷取網頁內容

In [9]:
import requests
a=requests.get("https://www.google.com.tw/")
print(a.text)

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="zh-TW"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="NcCtfVDFCk3VQfFR/m4vxw==">(function(){window.google={kEI:'3fYBXcqrLMGJ8wWMu4zQAQ',kEXPI:'0,1353804,51,1906,1019,1404,1225,730,224,1575,3151,379,206,1017,620,496,79,277,5,7,32,207,22,1133968,1197879,329532,1294,12383,4855,22661,10030,15248,867,2236,9927,12923,1401,2197,369,3314,5505,2436,266,5107,575,835,284,2,579,727,2431,1362,4323,4968,773,2255,5890,2,1749,2811,3601,669,1050,1808,1397,81,7,491,620,29,10304,1288,2,4007,796,101,1119,38,920,746,7,120,1217,1364,1611,2736,49,3012,2,631,2562,2,4,2,671,43,4148,635,2607,632,1845,383,655,19,320,1565,416,142,86,2,1159,777,1,150,1,217,1017,300,1461,98,36,2,354,29,400,992,509,598,10,168,8,109,187,831,235,807,453,174,967,48,553,11,14,10,657,612,1831,381,25,177,167,1

# 單行註解 多行註解 變數設定

In [10]:
#單行註解
'''
多行註解
'''
#變數設定
X=0
print(X)

0


In [12]:
x,y,z=1,2,3
x+=2
y*=2
z**=2
print(x,y,z)

3 4 9


# 如何使用數學運算式子以及利用ID來查詢內存位置

In [13]:
import math
a,b,c=3,4,5
s=(a+b+c)/2
d=math.sqrt(s*(s-a)*(s-b)*(s-c))
print(d)
id(a)

6.0


140729278378896

# 使用數學式子PI(圓周率)

In [14]:
import math
print((4.5*4.5*math.pi*4.5)/3)

95.42587685278995


# 如何使用除法、取商及取餘數的語法

In [15]:
x=16
y=3
print(x/y)
print(x//y)
print(x%y)

5.333333333333333
5
1


# 解釋宣告時使用int、float函式的差別
# 利用str()以及repr()表示兩者輸出的差別

In [16]:
x=12
y=float(x)+0.5
print(y)
print(int('123'))
print(float('123'))
print(int(123.333))
x=10*3.25
y=200*200
s='The value of x is ' + str(x) + ' and y is ' + str(y)
s1='The value of x is ' + str(x) + ' and y is ' + str(y)
print(s)
print(s1)

12.5
123
123.0
123
The value of x is 32.5 and y is 40000
The value of x is 32.5 and y is 40000


In [17]:
import math
r=input("請輸入半徑")
area=float(r)*float(r)*math.pi
print("園面積為:" ,area)

請輸入半徑5
園面積為: 78.53981633974483


# 使用LIST並且介紹該功能

In [23]:
my_list0 = [1,2,3]
print(my_list0)
my_list1=['python','js','SQL']
print(my_list1[0])
my_list1.append('java')
print(my_list1)

[1, 2, 3]
python
['python', 'js', 'SQL', 'java']


# 介紹LEN的功能 能夠輸出LIST中含有幾筆資料

In [24]:
my_list2=['C#','python','js','SQL','java']
print(len(my_list2))

5


# 教導如何移除在LIST中指定的字串 以及刪除指定的陣列位置

In [26]:
my_list3=['C#','python','js','SQL','java']
my_list3.remove('js')
print(my_list3)
del my_list3[0]
print(my_list3)
del my_list3[-1]
print(my_list3)

['C#', 'python', 'SQL', 'java']
['python', 'SQL', 'java']
['python', 'SQL']


# 介紹陣列能透過數學式子來影響內容

In [38]:
a=[1,2]
print(a * 5)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


介紹在陣列中能使用冒號(:)來擷取指定範圍的陣列內容
超過兩個冒號能夠給予間隔
DEL能夠刪除指定的陣列
MAX()能夠在陣列中找出最大值
MIN()找出最小值
COUNT()可以計算括號中指定字串/數字的出現次數
reverse()能夠將陣列反轉
sort()能夠將陣列做排序

In [45]:
a=[1,2,3,4,5,6,7,8,9]
b=a[0:3]
print(b)
c=a[0:9:2]
print(c)

del a [7:9]
print(a)
#print(max(a))
print(min(a))
print(a.index(1))
print(a.count(1))

print(a)
a.reverse()
print(a)
a.sort()
print(a)

[1, 2, 3]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7]
1
0
1
[1, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7]


# 示範陣列中能夠同時存取字串及數字

In [46]:
a=[123,'abc',[111,222],[333,444]]
print(a[0])
print(a[1])
print(a[2])
print(a[2][1])

123
abc
[111, 222]
222


# 使用ITEM函式，透過PRINT能夠將陣列中每個資料做好排列做輸出

In [47]:
shoplist=['milk','egg','coffee','watermelon']
for item in shoplist:
    print(item)

milk
egg
coffee
watermelon


# 介紹TUPLE與LIST的差異，以及TYPE能夠查詢該變數屬於什麼類型

In [48]:
a_list=['python','js','c#']
a_tuple=['python','js','c#']
b_tuple=tuple(a_list)
print(type(a_list))
print(type(b_tuple))
print(b_tuple)

<class 'list'>
<class 'tuple'>
('python', 'js', 'c#')


In [50]:
c_tuple=111,222,333
print(c_tuple)
print(type(c_tuple))

(111, 222, 333)
<class 'tuple'>


# dict(字典-dictionary)帶有鍵值(key)的list

In [52]:
a_list=['python','js','c#']
a_dict={0:'python',1:'js',2:'c#'}
print(a_list[0])
print(a_dict[0])
b_dict={'1st':'python','2md':'js','3rd':'c#'}
print(b_dict['1st'])

python
python
python


# 溫度

In [53]:
celsius=float(input('請輸入攝氏溫度'))
fahrenheit=(9/5) * celsius + 32
print('華氏溫度為:',fahrenheit)

請輸入攝氏溫度10
華氏溫度為: 50.0


In [55]:
import statistics as st
sample=[5,8,9,6,4,1,2,3,5,6]
print('樣本=',sample)
print('平均數=',st.mean(sample))
#print('最大數=',max(sample))
print('最小數=',min(sample))
print('變異數=',round(st.variance(sample),2))
print('標準差=',round(st.stdev(sample),2))

樣本= [5, 8, 9, 6, 4, 1, 2, 3, 5, 6]
平均數= 4.9
最小數= 1
變異數= 6.32
標準差= 2.51


In [56]:
numA = int(input('請輸入numA'))
numB = int(input('請輸入numB'))
if numA < numB:
    print('numB是比較大的數')
elif numA>numB:
    print('numA是比較大的數')
else:
    print('兩數相同')

請輸入numA10
請輸入numB20
numB是比較大的數


In [57]:
sum=0
for i in range(1,11):
    sum=sum + i
print('總和:',sum)

總和: 55


In [1]:
sum=0
count=1
while count <=10:
    sum=sum+count #sum += count
    count+=1
print('1+2+3+...+10=',sum)


1+2+3+...+10= 55


# 銀行利息規範

In [2]:
x = 10000
year = 0
while x < 20000:
    year +=1
    x=x * 1.0104
print(str(year),'年後，存款金額加倍')

67 年後，存款金額加倍


 # 帳號密碼程式

In [3]:
id='tony'
pwd='1234'
while True:
    x=input('請輸入帳號:')
    y=input('請輸入密碼:')
    if(x==id and y==pwd):
        print('歡迎登入')
        break
    else:
        print('帳號/密碼輸入錯誤')

請輸入帳號:tony
請輸入密碼:1234
歡迎登入


# break, continue,pass範例

In [4]:

mylist=['C#','Python','java','C++']
for i in mylist:
    if i == 'java':
        break
    else:
        print(i)

C#
Python


In [5]:
import random
for i in range(0,10):
    print(random.random())

0.5629529733559492
0.659915170182292
0.05020740876568963
0.6601113013252917
0.5729450664658399
0.09027701012812295
0.2083486557715104
0.7073130818397856
0.29527062599460285
0.5451237469656581


In [6]:
for i in range(0,10):
    print(random.randint(1,9))

7
7
4
9
4
4
5
8
7
2


In [7]:
import random
number=random.randint(1,99)
while True:
    guess=input('請輸入1-99的數字(q離開):')
    if guess =='q':
        print('離開遊戲,正確數字是',number)
        break
    else:
        if number==int(guess):
            print('恭喜,猜對了')
            break
        else:
            print('猜錯了')


請輸入1-99的數字(q離開):q
離開遊戲,正確數字是 34


# numpy套件

In [8]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# numpy套件ndarray型態，提供eLement-wise的操作

In [9]:
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)
print(type(a_ndarray))
print(a_ndarray.ndim) #ndarray的維度
print(a_ndarray.shape) #ndarray的shape
print(a_ndarray.dtype) #ndarray的資料型態

[ 3  6  9 12 15]
<class 'numpy.ndarray'>
1
(5,)
int32


In [10]:
z=np.zeros(6)
print(z)# 六個元素都為0的1d ndarray
print(np.zeros((2,6))) #12個援助都為0的2d ndarray
print(np.empty((2,6,2))) #24個元素都未初始化的值 長,寬,RGB
print(np.arange(10)) #10個元素都維0-9的1d ndarray

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 3.56043053e-307]
  [1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307]
  [1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.33510679e-306]]

 [[2.22522597e-306 1.60220393e-306]
  [1.29060735e-306 1.11261570e-306]
  [7.56602523e-307 9.34609790e-307]
  [8.34451504e-308 1.27946076e-307]
  [1.33511562e-306 8.90103560e-307]
  [1.42410974e-306 3.23796840e-317]]]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


# 2維ndarray取值

In [13]:
my_2d_array = np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:]) #第二列資料
print(my_2d_array[:,1]) #第二欄資料
print(my_2d_array[1,1]) #第二列第二欄資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [14]:
#假設有六個組別"Modern Web", "DevOps","CLoud","Big Data","Security","自我挑戰組"
#其參加人數分別為56,8,19,14,6,71人
groups=["Modern Web", "DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironman=[56,8,19,14,6,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


# 用人數去篩選組別

In [15]:
print(ironman_array >=10)
print(groups_array[ironman_array >=10])
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarray轉置

In [16]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [17]:
print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


# ndarray nan(空值)

In [18]:
nan_array=np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


# 第六章

In [19]:
import pandas as pd
import numpy as np
groups = ["Modern Web","DevOps",np.nan,"Cloud","Big Data", "Security","自我挑戰組"]
ironmen = [59,9,19,14,6,77,np.nan]
ironmen_dict={
    "groups":groups,
    "ironmen":ironmen
}
ironmen_df = pd.DataFrame(ironmen_dict)

print(ironmen_df.loc[:,"groups"].isnull())
print(ironmen_df.loc[:,"ironmen"].notnull())

ironmen_df

0    False
1    False
2     True
3    False
4    False
5    False
6    False
Name: groups, dtype: bool
0     True
1     True
2     True
3     True
4     True
5     True
6    False
Name: ironmen, dtype: bool


groups  ironmen
0  Modern Web     59.0
1      DevOps      9.0
2         NaN     19.0
3       Cloud     14.0
4    Big Data      6.0
5    Security     77.0
6       自我挑戰組      NaN

In [30]:
print(ironmen_df.ndim)
print(ironmen_df.shape)
print(ironmen_df.dtypes)

2
(6, 1)
ironmen    int64
dtype: object


In [31]:
print(ironmen_df.sum())
print(ironmen_df.ironmen.sum())
print(ironmen_df.mean())
print(ironmen_df.median)
print(ironmen_df.describe())


ironmen    184
dtype: int64
184
ironmen    30.666667
dtype: float64
<bound method DataFrame.median of             ironmen
Modern Web       59
DevOps            9
Cloud            19
Big Data         14
Security          6
自我挑戰組            77>
         ironmen
count   6.000000
mean   30.666667
std    29.803803
min     6.000000
25%    10.250000
50%    16.500000
75%    49.000000
max    77.000000


a=ironmen_df.dropna()
b=ironmen_df.fillna(0)
c=ironmen_df.ironmen.fillna(ironmen_df.ironmen.mean)

# 空值補平均數

In [41]:
a

ironmen
Modern Web       59
DevOps            9
Cloud            19
Big Data         14
Security          6
自我挑戰組            77

In [42]:
b

ironmen
Modern Web       59
DevOps            9
Cloud            19
Big Data         14
Security          6
自我挑戰組            77

In [43]:
c

Modern Web    59
DevOps         9
Cloud         19
Big Data      14
Security       6
自我挑戰組         77
Name: ironmen, dtype: int64

In [36]:
import pandas as pd
groups = ["Modern Web","DevOps","Cloud","Big Data", "Security","自我挑戰組"]
ironmen = [59,9,19,14,6,77]
# 建立data frame
ironmen_df = pd.DataFrame(ironmen,columns=["ironmen"],index=groups)
ironmen_df.sort_index()

ironmen
Big Data         14
Cloud            19
DevOps            9
Modern Web       59
Security          6
自我挑戰組            77

In [44]:
ironmen_df.sort_values(by = "ironmen")

ironmen
Security          6
DevOps            9
Big Data         14
Cloud            19
Modern Web       59
自我挑戰組            77

# 雲端載入

In [3]:
import pandas as pd
url="https://storage.googleapis.com/2017_ithome_ironman/data/iris.csv"
iris_df = pd.read_csv(url)
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
iris_df.mean()
#取平均

Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [5]:
iris_df['Sepal.Length'].median()
#取中位數

5.8

# excel 檔案載入

In [7]:
import pandas as pd
iris_df=pd.read_csv('iris.csv')
iris_df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# CH8

# 自訂函數

In [13]:
import math
def circle(radius):
    area = radius * radius * math.pi
    return area
print(circle(10))

314.1592653589793


In [16]:
import math
def circle(radius):
    area = radius * radius * math.pi
    return area
r=input("請輸入圓的半徑")
print("圓面積為:",circle(float(r)))

請輸入圓的半徑12.3
圓面積為: 475.2915525615999


In [12]:
import random
def exchange_sort(input_list):
    a=input_list
    for i in range(0, len(input_list)-1):
        for j in range (i+1, len(input_list)):
            if a[i]>a[j]:#>,<互換換成大小排序
                a[i],a[j]=a[j],a[i]
    return a

my_vector = random.sample(range(0,100),10)
print(my_vector)
print(exchange_sort(my_vector))

[41, 77, 90, 65, 70, 71, 30, 36, 29, 40]
[29, 30, 36, 40, 41, 65, 70, 71, 77, 90]


In [1]:
def max(m,n):
    return m if m > n else n
print(max(10,3))

10


In [2]:
#Lambda 寫法
max = lambda m,n: m if m>n else n
print(max(10,3))

10


In [7]:
#List * 5
a=[1,2,3,4,5]
print(a*5)
#numbpy * 5
import numpy as np
b=np.array(a)
print(b*5)
#Lamda 寫法
c=list(map(lambda x: x*5, a)) #map(function,data)
print(c)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[5, 10, 15, 20, 25]


# 錯誤處理 try: except:

In [8]:
def circle(radius):
    try:
        return radius * radius * 3.14
    except:
        return "請輸入數值"
    
print(circle(10))
print(circle('十'))

314.0
請輸入數值
